# Generated by Django 3.0.4 on 2020-03-31 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teerresults', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='title',
            field=models.CharField(choices=[('JTR', 'JUWAI TEER RESULT'), ('KTR', 'KHANAPARA TEER RESULT'), ('STR', 'SHILLONG TEER RESULT'), ('JLTR', 'JOWAI-LADRYMBAI TEER RESULT'), ('NTR', 'NIGHT TEER RESULT')], max_length=20),
        ),
    ]
