# Generated by Django 3.0.4 on 2020-04-01 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teerresults', '0005_resultlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resultlist',
            old_name='title1',
            new_name='FR',
        ),
        migrations.RenameField(
            model_name='resultlist',
            old_name='title2',
            new_name='SR',
        ),
    ]
