# Generated by Django 3.0.4 on 2020-04-02 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teerresults', '0006_auto_20200401_0829'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('KTR', 'KHANAPARA TEER RESULT'), ('STR', 'SHILLONG TEER RESULT')], max_length=32)),
                ('direct', models.CharField(max_length=10)),
                ('house', models.IntegerField()),
                ('ending', models.IntegerField()),
            ],
        ),
    ]
